### ISSUE TITLE
Move $bourbon; to the top of the list.

### ISSUE THREAD

**Issue by whmii** [thoughtbot/bourbon.io#22]
I think it would be good have the first section be the docs for the `$bourbon` settings variable (I mean, until we add some installation instructions sections). Right now it is kind of buried.

I think we should have a section for 'settings' and then what ever we decide for the res of them, 'Functions and Mixins'? ¯_(ツ)_/¯

**Comment by enatario** [comment]
We are [no longer maintaining this repo](https://github.com/thoughtbot/bourbon.io/pull/203) or [Bourbon itself](https://github.com/thoughtbot/bourbon?tab=readme-ov-file#deprecated-as-of-september-13-2024), so closing this!
