### ISSUE TITLE
Fix "view source" link at Linear Gradient documentation

### ISSUE THREAD

**Issue by rafaellyra** [thoughtbot/bourbon.io#5]
The "view source" link is refering to `https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/functions/_linear-gradient.scss` and the correct is `https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/css3/_linear-gradient.scss`.

**Comment by tysongach** [comment]
This repo is not the current Bourbon website. We’ll get this fixed over in the [Bourbon repo](https://github.com/thoughtbot/bourbon).
