### ISSUE TITLE
Documentation site doesn't work well in mobile 

### ISSUE THREAD

**Issue by dented42** [thoughtbot/bourbon.io#6]
I'm on an iPhone running iOS 8, and the navigation sidebar doesn't render properly, when I begin to scroll to the right to look at the content, the sidebar obscures the content. It slides to the left, but not fast enough.

**Comment by tysongach** [comment]
Yeah, it’s not really optimized for mobile. But this actually the repo for the _new_ website and documentation we are working on. It’ll be fixed!
