### ISSUE TITLE
Wrong order of triangle arg for Bourbon 5.0 netlify docs

### ISSUE THREAD

**Issue by nickngqs** [thoughtbot/bourbon.io#69]
From [http://bourbon.netlify.com/docs/5.0.0/#triangle](http://bourbon.netlify.com/docs/5.0.0/#triangle)
`@include triangle("up", 2rem, 1rem, #b25c9c);`

Should be...
`@include triangle("up", #b25c9c, 2rem, 1rem);`

**Comment by tysongach** [comment]
Hi @nickngqs!

We’ll update that when we cut a new release of Bourbon. Currently, that change is only reflected on the `master` branch.

**Comment by nickngqs** [comment]
Nice! Can't wait for the new release!
