### ISSUE TITLE
Link to our code of conduct

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/bourbon.io#71]
https://thoughtbot.com/open-source-code-of-conduct

**Comment by whmii** [comment]
clappy clap 👏

**Comment by whmii** [comment]
@tysongach what do you think would be a good way to articulate the link? Perhaps…

> All contributors of XXXX abide by the thoughtbot [code of conduct](#).

**Comment by tysongach** [comment]
I was just going to put a `Code of Conduct` link in the footer.
