### ISSUE TITLE
Are the Bourbon 5 docs online?

### ISSUE THREAD

**Issue by talsafran** [thoughtbot/bourbon.io#79]
Hi! Apologize in advance if this is a silly question, but I noticed that the only way to access the Bourbon 5 docs is to build them from this repo and run locally.

Are they online anywhere? The [bourbon.io website](http://bourbon.io) still lists 4.x but with ~90% deprecation warnings:

![](https://dl.dropboxusercontent.com/spa/tcdy8ht0a6rx05q/jzdl22oh.png)

Thanks in advance!

**Comment by tysongach** [comment]
Yep, they are a WIP, but available here: http://bourbon.netlify.com/docs/latest/
